name: Package

on:
  create:
    tags:
      - v*.*.*

jobs:
  bake:
    runs-on: blg-runner-set
    steps:
      - name: Ensure new enough git version is installed.
        run: |
          apt update
          apt install -y git

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.CONTENT_REPO_GITHUB_TOKEN }}

      - name: Set TAG environment variable
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v4
        with:
          push: true

